// Pyodide web worker: loads omnibenchmark and converts YAML → Snakefile preview

importScripts("https://cdn.jsdelivr.net/pyodide/v0.27.3/full/pyodide.js");

let pyodide = null;

// Python code stored as a regular (non-template) string to avoid escaping hell.
// Each \n is a real JS escape → newline.  Each \\ is a literal backslash.
// Python sees exactly what's written here.
const PREVIEW_PY = [
  "import io, json, warnings, re, hashlib, gzip, base64",
  "import yaml as _yaml",
  "from pathlib import PurePosixPath",
  "warnings.filterwarnings('ignore')",
  "",
  "def _repo_name(url):",
  "    name = PurePosixPath(url.rstrip('/')).name",
  "    return name[:-4] if name.endswith('.git') else name",
  "",
  "def _rulename(node_id):",
  "    name = node_id.replace('-', '_').replace('.', '_')",
  "    return ('rule_' + name) if name and not name[0].isalpha() else name",
  "",
  "def _ikey(entry):",
  "    return re.sub(r'[^a-zA-Z0-9_]', '_', entry)",
  "",
  "def _env_dir(bench, module):",
  "    eid = module.software_environment",
  "    if not eid: return ''",
  "    env = next((e for e in bench.software_environments if e.id == eid), None)",
  "    if not env: return ''",
  "    b = bench.software_backend.value",
  "    if b == 'conda' and env.conda:",
  "        return f'    conda: \"{env.conda}\"\\n'",
  "    if b == 'apptainer' and env.apptainer:",
  "        return f'    container: \"{env.apptainer}\"\\n'",
  "    if b == 'envmodules' and env.envmodule:",
  "        return f'    envmodules: \"{env.envmodule}\"\\n'",
  "    return ''",
  "",
  "def _res_dir(r):",
  "    if not r: return ''",
  "    lines = ['    resources:']",
  "    lines.append(f'        cores={r.cores or 2},')",
  "    if r.mem_mb:  lines.append(f'        mem_mb={r.mem_mb},')",
  "    if r.disk_mb: lines.append(f'        disk_mb={r.disk_mb},')",
  "    if r.runtime: lines.append(f'        runtime={r.runtime},')",
  "    if r.gpu:     lines.append(f'        nvidia_gpu={r.gpu},')",
  "    return '\\n'.join(lines) + '\\n'",
  "",
  "def _generate(bench):",
  "    from omnibenchmark.model.params import Params",
  "    out = io.StringIO()",
  "    backend = bench.software_backend.value",
  "    out.write(f'# OmniBenchmark: {bench.id} v{bench.version}\\n')",
  "    out.write(f'# Benchmarker: {bench.benchmarker}\\n')",
  "    out.write(f'# Backend: {backend}\\n')",
  "    out.write('# Entrypoints are read from each module\\'s omnibenchmark.yaml by run.sh.\\n')",
  "    out.write('\\n')",
  "    out.write('configfile: \"module_config.json\"\\n\\n')",
  "    # Build all nodes in stage order — mirrors production run.py path logic",
  "    all_nodes = []",
  "    prev_stage_nodes = []",
  "    for stage in bench.stages:",
  "        current_stage_nodes = []",
  "        input_ids = [e for ic in (stage.inputs or []) for e in ic.entries]",
  "        for module in stage.modules:",
  "            if module.parameters:",
  "                params_list = []",
  "                for param in module.parameters:",
  "                    params_list.extend(Params.expand_from_parameter(param))",
  "            else:",
  "                params_list = [None]",
  "            input_node_list = prev_stage_nodes if (input_ids and prev_stage_nodes) else [None]",
  "            for input_node in input_node_list:",
  "                for params in params_list:",
  "                    param_id = f'.{params.hash_short()}' if params else '.default'",
  "                    inputs = {}",
  "                    imap   = {}",
  "                    base_path = None",
  "                    if input_node:",
  "                        for iid in input_ids:",
  "                            skey = _ikey(iid)",
  "                            ipath = input_node['omap'].get(iid)",
  "                            if ipath:",
  "                                inputs[skey] = ipath",
  "                                imap[skey]   = iid",
  "                        if inputs:",
  "                            deepest = max(inputs.values(), key=lambda p: p.count('/'))",
  "                            base_path = '/'.join(deepest.split('/')[:-1])",
  "                    dataset = input_node['dataset'] if input_node else module.id",
  "                    outputs = []",
  "                    omap = {}",
  "                    for outf in (stage.outputs or []):",
  "                        fname = outf.path.replace('{dataset}', dataset)",
  "                        if base_path:",
  "                            opath = f\"{base_path}/{stage.id}/{module.id}/{param_id}/{fname}\"",
  "                        else:",
  "                            opath = f\"{stage.id}/{module.id}/{param_id}/{fname}\"",
  "                        outputs.append(opath)",
  "                        omap[outf.id] = opath",
  "                    if input_node:",
  "                        node_id = f\"{input_node['node_id']}-{stage.id}-{module.id}{param_id}\"",
  "                    else:",
  "                        node_id = f\"{stage.id}-{module.id}{param_id}\"",
  "                    node = {",
  "                        'node_id': node_id,",
  "                        'stage': stage,",
  "                        'module': module,",
  "                        'param_id': param_id,",
  "                        'params': params,",
  "                        'inputs': inputs,",
  "                        'imap': imap,",
  "                        'outputs': outputs,",
  "                        'omap': omap,",
  "                        'dataset': dataset,",
  "                    }",
  "                    all_nodes.append(node)",
  "                    current_stage_nodes.append(node)",
  "        prev_stage_nodes = current_stage_nodes",
  "    # rule all",
  "    out.write('rule all:\\n    input:\\n')",
  "    for node in all_nodes:",
  "        for opath in node['outputs']:",
  "            out.write(f'        \"{opath}\",\\n')",
  "    out.write('    default_target: True\\n\\n\\n')",
  "    # Individual rules",
  "    prev_stage_id = None",
  "    for node in all_nodes:",
  "        stage   = node['stage']",
  "        module  = node['module']",
  "        params  = node['params']",
  "        inputs  = node['inputs']",
  "        imap    = node['imap']",
  "        outputs = node['outputs']",
  "        dataset = node['dataset']",
  "        if stage.id != prev_stage_id:",
  "            out.write(f'# {\"=\" * 60}\\n# Stage: {stage.id}\\n# {\"=\" * 60}\\n\\n')",
  "            prev_stage_id = stage.id",
  "        res       = module.resources or stage.resources",
  "        repo_slug = _repo_name(module.repository.url)",
  "        commit    = module.repository.commit[:7]",
  "        ekey      = module.repository.entrypoint or 'default'",
  "        rule      = _rulename(node['node_id'])",
  "        cli_str   = ' '.join(params.to_cli_args()) if params else ''",
  "        output_dir = '/'.join(outputs[0].split('/')[:-1]) if outputs else '.'",
  "        out.write(f'rule {rule}:\\n')",
  "        if inputs:",
  "            out.write('    input:\\n')",
  "            for skey, ipath in inputs.items():",
  "                out.write(f'        {skey}=\"{ipath}\",\\n')",
  "        out.write('    output:\\n')",
  "        for opath in outputs:",
  "            out.write(f'        \"{opath}\",\\n')",
  "        out.write('    params:\\n')",
  "        out.write(f'        module_dir=\".modules/{repo_slug}/{commit}/\",\\n')",
  "        out.write(f'        entrypoint=config[\"entrypoints\"][\"{module.id}\"][\"{ekey}\"],\\n')",
  "        out.write(f'        output_dir=\"{output_dir}\",\\n')",
  "        out.write(f'        cli_args=\"{cli_str}\",\\n')",
  "        out.write(f'    benchmark:\\n        \"{output_dir}/{dataset}_performance.txt\"\\n')",
  "        out.write(f'    log:\\n        \".logs/{rule}.log\"\\n')",
  "        ed = _env_dir(bench, module)",
  "        if ed: out.write(ed)",
  "        rd = _res_dir(res)",
  "        if rd: out.write(rd)",
  "        out.write('    shell:\\n        \"\"\"\\n')",
  "        out.write('        mkdir -p {params.output_dir} $(dirname {log})\\n')",
  "        out.write('        OUTPUT_DIR=$(cd {params.output_dir} && pwd)\\n')",
  "        for skey in inputs:",
  "            out.write(f'        INPUT_{skey}=$(cd $(dirname {{input.{skey}}}) && pwd)/$(basename {{input.{skey}}})\\n')",
  "        out.write('        LOG_FILE=$(pwd)/{log}\\n')",
  "        out.write('        exec > >(tee \"$LOG_FILE\") 2>&1\\n')",
  "        out.write(\"        echo '=== Rule: {rule} ==='\\n\")",
  "        out.write(\"        echo 'Started:' $(date -Iseconds)\\n\")",
  "        out.write(\"        echo '---'\\n\")",
  "        out.write('        cd {params.module_dir}\\n')",
  "        out.write('        python3 {params.entrypoint} \\\\\\n')",
  "        out.write('        --output_dir $OUTPUT_DIR \\\\\\n')",
  "        out.write(f'        --name {dataset} \\\\\\n')",
  "        for skey, iid in imap.items():",
  "            out.write(f'        --{iid} $INPUT_{skey} \\\\\\n')",
  "        out.write('        {params.cli_args}\\n')",
  "        out.write('        \"\"\"\\n\\n')",
  "    stats = {'total': len(all_nodes), 'stages': len(bench.stages), 'by_stage': {}}",
  "    for _n in all_nodes:",
  "        sid = _n['stage'].id",
  "        stats['by_stage'][sid] = stats['by_stage'].get(sid, 0) + 1",
  "    return out.getvalue(), stats",
  "",
  "def _generate_mermaid(bench):",
  "    stage_outs = {}",
  "    for stage in bench.stages:",
  "        stage_outs[stage.id] = {o.id for o in (stage.outputs or [])}",
  "    lines = ['flowchart LR']",
  "    for stage in bench.stages:",
  "        lines.append(f'    subgraph sg_{stage.id}[{stage.id}]')",
  "        for module in stage.modules:",
  "            nid = 'n_' + stage.id + '_' + module.id.replace('-','_').replace('.','_')",
  "            lines.append(f'        {nid}[\"{module.id}\"]')",
  "        lines.append('    end')",
  "    added = set()",
  "    for stage in bench.stages:",
  "        input_ids = {e for ic in (stage.inputs or []) for e in ic.entries}",
  "        for prev in bench.stages:",
  "            if prev.id == stage.id: continue",
  "            if input_ids & stage_outs.get(prev.id, set()):",
  "                key = (prev.id, stage.id)",
  "                if key not in added:",
  "                    added.add(key)",
  "                    lines.append(f'    sg_{prev.id} --> sg_{stage.id}')",
  "    return '\\n'.join(lines)",
  "",
  "def _generate_runner(bench):",
  "    out = io.StringIO()",
  "    backend = bench.software_backend.value",
  "    out.write('#!/usr/bin/env bash\\n')",
  "    out.write(f'# OmniBenchmark run script: {bench.id} v{bench.version}\\n')",
  "    out.write(f'# Benchmarker: {bench.benchmarker}\\n')",
  "    out.write('# Generated by OBEditor\\n')",
  "    out.write('#\\n')",
  "    out.write('# Usage: bash run.sh [CORES]\\n')",
  "    out.write('# Expects: Snakefile in cwd, git + snakemake in PATH\\n')",
  "    out.write('set -euo pipefail\\n\\n')",
  "    out.write('CORES=\"${1:-4}\"\\n')",
  "    out.write('MODULES_DIR=\".modules\"\\n\\n')",
  "    # clone helper",
  "    out.write('# ── Module resolution ──────────────────────────────────────────────────\\n')",
  "    out.write('mkdir -p \"$MODULES_DIR\"\\n\\n')",
  "    out.write('clone_module() {\\n')",
  "    out.write('    local name=\"$1\" url=\"$2\" repo=\"$3\" commit=\"$4\"\\n')",
  "    out.write('    local dest=\"$MODULES_DIR/$repo/$commit\"\\n')",
  "    out.write('    if [ -d \"$dest/.git\" ]; then\\n')",
  "    out.write('        echo \"  already resolved: $name\"\\n')",
  "    out.write('        return 0\\n')",
  "    out.write('    fi\\n')",
  "    out.write('    echo \"  cloning $name -> $dest\"\\n')",
  "    out.write('    mkdir -p \"$(dirname \"$dest\")\"\\n')",
  "    out.write('    git clone --filter=blob:none --no-checkout \"$url\" \"$dest\"\\n')",
  "    out.write('    git -C \"$dest\" checkout \"$commit\"\\n')",
  "    out.write('}\\n\\n')",
  "    out.write('echo \"=== Resolving modules ===\"\\n')",
  "    seen = set()",
  "    for stage in bench.stages:",
  "        out.write(f'\\n# Stage: {stage.id}\\n')",
  "        for module in stage.modules:",
  "            commit = module.repository.commit",
  "            url = module.repository.url",
  "            repo = _repo_name(url)",
  "            key = (repo, commit[:7])",
  "            if key not in seen:",
  "                seen.add(key)",
  "                out.write(f'clone_module \"{module.id}\" \"{url}\" \"{repo}\" \"{commit[:7]}\"\\n')",
  "    if bench.metric_collectors:",
  "        out.write('\\n# Metric collectors\\n')",
  "        for mc in bench.metric_collectors:",
  "            commit = mc.repository.commit",
  "            url = mc.repository.url",
  "            repo = _repo_name(url)",
  "            key = (repo, commit[:7])",
  "            if key not in seen:",
  "                seen.add(key)",
  "                out.write(f'clone_module \"{mc.id}\" \"{url}\" \"{repo}\" \"{commit[:7]}\"\\n')",
  "    out.write('\\necho \"=== All modules resolved ===\"\\n\\n')",
  "    # Generate module_config.json by reading omnibenchmark.yaml from each cloned module",
  "    out.write('# ── Generate module_config.json ────────────────────────────────────────\\n')",
  "    out.write('echo \"=== Reading entrypoints ===\"\\n')",
  "    out.write('python3 << \\'PYEOF\\'\\n')",
  "    out.write('import yaml, json, sys\\n')",
  "    out.write('\\n')",
  "    out.write('modules = {\\n')",
  "    seen2 = set()",
  "    for stage in bench.stages:",
  "        for module in stage.modules:",
  "            repo = _repo_name(module.repository.url)",
  "            commit = module.repository.commit[:7]",
  "            ekey = module.repository.entrypoint or 'default'",
  "            if module.id not in seen2:",
  "                seen2.add(module.id)",
  "                out.write(f'    \"{module.id}\": (\".modules/{repo}/{commit}/omnibenchmark.yaml\", \"{ekey}\"),\\n')",
  "    if bench.metric_collectors:",
  "        for mc in bench.metric_collectors:",
  "            repo = _repo_name(mc.repository.url)",
  "            commit = mc.repository.commit[:7]",
  "            ekey = mc.repository.entrypoint or 'default'",
  "            if mc.id not in seen2:",
  "                seen2.add(mc.id)",
  "                out.write(f'    \"{mc.id}\": (\".modules/{repo}/{commit}/omnibenchmark.yaml\", \"{ekey}\"),\\n')",
  "    out.write('}\\n')",
  "    out.write('\\n')",
  "    out.write('result = {}\\n')",
  "    out.write('for mid, (yaml_path, ekey) in modules.items():\\n')",
  "    out.write('    try:\\n')",
  "    out.write('        cfg = yaml.safe_load(open(yaml_path))\\n')",
  "    out.write('        eps = cfg.get(\"entrypoints\", {})\\n')",
  "    out.write('        result[mid] = eps\\n')",
  "    out.write('        print(f\"  {mid}: {eps.get(ekey, list(eps.values())[0] if eps else \\\"run.py\\\")}\")\\n')",
  "    out.write('    except Exception as e:\\n')",
  "    out.write('        print(f\"  WARNING: {mid}: could not read {yaml_path}: {e}\", file=sys.stderr)\\n')",
  "    out.write('        result[mid] = {\"default\": \"run.py\"}\\n')",
  "    out.write('\\n')",
  "    out.write('with open(\"module_config.json\", \"w\") as f:\\n')",
  "    out.write('    json.dump({\"entrypoints\": result}, f, indent=2)\\n')",
  "    out.write('print(\"  Wrote module_config.json\")\\n')",
  "    out.write('PYEOF\\n\\n')",
  "    # snakemake invocation",
  "    out.write('# ── Snakemake execution ────────────────────────────────────────────────\\n')",
  "    out.write('echo \"=== Running snakemake (cores=$CORES) ===\"\\n')",
  "    flags = ['--snakefile Snakefile', '--cores \"$CORES\"', '--rerun-incomplete']",
  "    if backend == 'conda':       flags.append('--use-conda')",
  "    elif backend == 'apptainer': flags.append('--use-singularity')",
  "    elif backend == 'envmodules':flags.append('--use-envmodules')",
  "    out.write('snakemake \\\\\\n')",
  "    for flag in flags[:-1]:",
  "        out.write(f'    {flag} \\\\\\n')",
  "    out.write(f'    {flags[-1]}\\n')",
  "    return out.getvalue()",
  "",
  "def _normalize_yaml(text):",
  "    norm = '\\n'.join(line.rstrip() for line in text.splitlines())",
  "    if not norm.endswith('\\n'): norm += '\\n'",
  "    return norm",
  "",
  "def _parent_hash(text):",
  "    return hashlib.sha256(_normalize_yaml(text).encode('utf-8')).hexdigest()",
  "",
  "def _wizard(bench):",
  "    from omnibenchmark.model.params import Params",
  "    out = []",
  "    for stage in bench.stages:",
  "        mods = []",
  "        for m in stage.modules:",
  "            entry = {'id': m.id, 'name': (getattr(m, 'name', None) or m.id), 'params': None}",
  "            if m.parameters:",
  "                seen = set(); combos = []",
  "                for pset in m.parameters:",
  "                    try:",
  "                        for p in Params.expand_from_parameter(pset):",
  "                            h = p.hash_short()",
  "                            if h in seen: continue",
  "                            seen.add(h)",
  "                            combos.append({'hash': h,",
  "                                           'items': {k: v for k, v in p.items()},",
  "                                           'cli': ' '.join(p.to_cli_args())})",
  "                    except Exception: pass",
  "                entry['params'] = combos",
  "            mods.append(entry)",
  "        out.append({'id': stage.id, 'modules': mods})",
  "    return out",
  "",
  "def yaml_to_snakefile(yaml_content):",
  "    try:",
  "        from omnibenchmark.model.benchmark import Benchmark",
  "        bench = Benchmark.from_yaml(yaml_content)",
  "        snakefile, stats = _generate(bench)",
  "        mermaid = _generate_mermaid(bench)",
  "        raw = _yaml.safe_load(yaml_content)",
  "        canonical_url = None",
  "        if isinstance(raw, dict):",
  "            canonical_url = raw.get('canonical-url') or raw.get('canonical_url')",
  "        return {'ok': True, 'snakefile': snakefile, 'runner': _generate_runner(bench),",
  "                'stats': json.dumps(stats), 'mermaid': mermaid,",
  "                'wizard': json.dumps(_wizard(bench)),",
  "                'parent_hash': _parent_hash(yaml_content),",
  "                'parent_url': canonical_url}",
  "    except Exception as e:",
  "        import traceback",
  "        line = None",
  "        if hasattr(e, 'problem_mark') and e.problem_mark:",
  "            line = e.problem_mark.line + 1",
  "        return {'ok': False, 'error': f'{type(e).__name__}: {e}',",
  "                'traceback': traceback.format_exc(), 'line': line}",
  "",
  "def filter_benchmark(yaml_content, picks_json, derived_from=None):",
  "    try:",
  "        from omnibenchmark.model.benchmark import Benchmark",
  "        from omnibenchmark.model.params import Params",
  "        picks = json.loads(picks_json)",
  "        raw = _yaml.safe_load(yaml_content)",
  "        if not isinstance(raw, dict):",
  "            return {'ok': False, 'error': 'YAML root must be a mapping'}",
  "        parent_hash = _parent_hash(yaml_content)",
  "        parent_url = raw.get('canonical-url') or raw.get('canonical_url')",
  "        # Re-parse via pydantic so we can re-expand parameter sets when needed.",
  "        bench = Benchmark.from_yaml(yaml_content)",
  "        param_obj_map = {}",
  "        for _st in bench.stages:",
  "            for _m in _st.modules:",
  "                param_obj_map[(_st.id, _m.id)] = (_m.parameters or [])",
  "        def _apply_spec(new_mod, sid, mid, spec):",
  "            psets = param_obj_map.get((sid, mid)) or []",
  "            if not new_mod.get('parameters') or not psets: return",
  "            if spec == 'all': return",
  "            if spec == 'first':",
  "                try:",
  "                    expanded = Params.expand_from_parameter(psets[0])",
  "                    if expanded:",
  "                        new_mod['parameters'] = [{k: [v] for k, v in expanded[0].items()}]",
  "                except Exception: pass",
  "                return",
  "            if isinstance(spec, list):",
  "                wanted = set(spec); seen = set(); kept = []",
  "                for ps in psets:",
  "                    try:",
  "                        for p in Params.expand_from_parameter(ps):",
  "                            h = p.hash_short()",
  "                            if h in wanted and h not in seen:",
  "                                seen.add(h)",
  "                                kept.append({k: [v] for k, v in p.items()})",
  "                    except Exception: pass",
  "                if kept: new_mod['parameters'] = kept",
  "        new_stages = []",
  "        for st in (raw.get('stages') or []):",
  "            sid = st.get('id')",
  "            stage_picks = picks.get(sid)",
  "            if not stage_picks: continue",
  "            modules = []",
  "            for m in (st.get('modules') or []):",
  "                mid = m.get('id')",
  "                if mid not in stage_picks: continue",
  "                spec = stage_picks[mid]",
  "                new_mod = dict(m)",
  "                _apply_spec(new_mod, sid, mid, spec)",
  "                modules.append(new_mod)",
  "            if not modules: continue",
  "            new_st = dict(st)",
  "            new_st['modules'] = modules",
  "            new_stages.append(new_st)",
  "        out = dict(raw)",
  "        out.pop('canonical-url', None); out.pop('canonical_url', None)",
  "        out.pop('derived-from', None); out.pop('derived_from', None)",
  "        subset = {'sha256': parent_hash}",
  "        if parent_url: subset['url'] = parent_url",
  "        out['subset-of'] = subset",
  "        if derived_from: out['derived-from'] = derived_from",
  "        out['stages'] = new_stages",
  "        # Reorder header keys for readability.",
  "        head_keys = ['id', 'name', 'description', 'benchmarker', 'version', 'subset-of', 'derived-from']",
  "        ordered = {}",
  "        for k in head_keys:",
  "            if k in out: ordered[k] = out.pop(k)",
  "        ordered.update(out)",
  "        filtered_yaml = _yaml.safe_dump(ordered, sort_keys=False, default_flow_style=False, width=120)",
  "        blob = {'v': 2, 'parent': {'sha256': parent_hash}, 'picks': picks}",
  "        if parent_url: blob['parent']['url'] = parent_url",
  "        if derived_from: blob['parent']['derived_from'] = derived_from",
  "        blob_json = json.dumps(blob, separators=(',', ':'), sort_keys=True)",
  "        packed = base64.urlsafe_b64encode(",
  "            gzip.compress(blob_json.encode('utf-8'), compresslevel=9, mtime=0)",
  "        ).decode('ascii').rstrip('=')",
  "        return {'ok': True, 'filtered_yaml': filtered_yaml, 'blob_json': blob_json,",
  "                'blob_packed': packed, 'parent_hash': parent_hash,",
  "                'parent_url': parent_url}",
  "    except Exception as e:",
  "        import traceback",
  "        return {'ok': False, 'error': f'{type(e).__name__}: {e}',",
  "                'traceback': traceback.format_exc()}",
].join("\n");

async function init(wheelUrl) {
  try {
    self.postMessage({ type: "status", message: "Loading Pyodide runtime…" });
    pyodide = await loadPyodide();

    self.postMessage({ type: "status", message: "Loading pydantic / PyYAML…" });
    await pyodide.loadPackage(["pydantic", "pyyaml"]);

    self.postMessage({ type: "status", message: "Fetching omnibenchmark wheel…" });
    // Fetch the wheel in JS and write it to Pyodide's virtual FS.
    // Wheels are zip files — adding the path to sys.path lets zipimport handle it.
    // This completely avoids micropip and its download/resolution issues.
    const resp = await fetch(wheelUrl);
    if (!resp.ok) throw new Error(`Failed to fetch wheel: ${resp.status} ${resp.statusText}`);
    const wheelBytes = new Uint8Array(await resp.arrayBuffer());
    pyodide.FS.writeFile("/omnibenchmark.whl", wheelBytes);

    self.postMessage({ type: "status", message: "Initialising omnibenchmark…" });
    await pyodide.runPythonAsync(`
import sys, types

# Wheel is a zip — zipimport picks it up automatically from sys.path
sys.path.insert(0, "/omnibenchmark.whl")

def _mock(name, **attrs):
    m = types.ModuleType(name)
    for k, v in attrs.items():
        setattr(m, k, v)
    sys.modules[name] = m
    return m

# Mock every heavy / C-extension dep that omnibenchmark imports but we don't need.
# (We only use omnibenchmark.model.benchmark.Benchmark — pure pydantic + PyYAML.)
for _n in [
    "spdx_license_list",
    "matplotlib", "matplotlib.pyplot", "matplotlib.patches",
    "matplotlib.lines", "matplotlib.colors", "matplotlib.cm",
    "pydot",
    "humanfriendly",
    "filelock",
    "dulwich", "dulwich.repo", "dulwich.errors", "dulwich.porcelain",
    "snakemake",
    "copier",
    "dotenv", "python_dotenv",
    "tqdm", "tqdm.auto",
    "click",
    "rich", "rich.console", "rich.table", "rich.panel", "rich.progress",
]:
    _mock(_n)

sys.modules["spdx_license_list"].LICENSES = {}

# Smoke-test: this is all we actually call at runtime
from omnibenchmark.model.benchmark import Benchmark
`);

    self.postMessage({ type: "status", message: "Initialising preview engine…" });
    await pyodide.runPythonAsync(PREVIEW_PY);

    const version = await pyodide.runPythonAsync(`
try:
    import importlib.metadata
    _ver = importlib.metadata.version('omnibenchmark')
except Exception:
    _ver = 'unknown'
_ver
`);
    self.postMessage({ type: "ready", version: String(version) });
  } catch (e) {
    self.postMessage({ type: "result", ok: false, error: String(e) });
  }
}

async function convert(yaml) {
  if (!pyodide) return;
  try {
    // Pass yaml via globals to avoid any quoting/injection issues
    pyodide.globals.set("_yaml_input", yaml);
    const result = await pyodide.runPythonAsync("yaml_to_snakefile(_yaml_input)");
    const obj = result.toJs({ dict_converter: Object.fromEntries });
    result.destroy();
    self.postMessage({ type: "result", ok: obj.ok, snakefile: obj.snakefile, runner: obj.runner, stats: obj.stats, mermaid: obj.mermaid, error: obj.error, line: obj.line, wizard: obj.wizard, parent_hash: obj.parent_hash, parent_url: obj.parent_url });
  } catch (e) {
    self.postMessage({ type: "result", ok: false, error: e.message });
  }
}

async function filterCmd({ yaml, picks, derivedFrom }) {
  if (!pyodide) return;
  try {
    pyodide.globals.set("_yaml_input", yaml);
    pyodide.globals.set("_picks_json", JSON.stringify(picks));
    pyodide.globals.set("_derived_from", derivedFrom || null);
    const result = await pyodide.runPythonAsync("filter_benchmark(_yaml_input, _picks_json, _derived_from)");
    const obj = result.toJs({ dict_converter: Object.fromEntries });
    result.destroy();
    self.postMessage({ type: "filtered", ok: obj.ok, filtered_yaml: obj.filtered_yaml, blob_json: obj.blob_json, blob_packed: obj.blob_packed, parent_hash: obj.parent_hash, parent_url: obj.parent_url, error: obj.error });
  } catch (e) {
    self.postMessage({ type: "filtered", ok: false, error: e.message });
  }
}

self.onmessage = async ({ data }) => {
  if (data.type === "init")    await init(data.wheelUrl);
  if (data.type === "convert") await convert(data.yaml);
  if (data.type === "filter")  await filterCmd(data);
};
